### ONYXDATADNA CHALLENGE JULY 2026

### **1. Business Understanding**
#### **Project Objective**

The objective of this project is to analyze the impact of artificial intelligence (AI) adoption on the global workforce between 2021 and 2024. Using workforce data across countries, industries, and skill categories, the analysis aims to identify trends in AI adoption, evaluate changes in employment and workforce readiness, and examine how the emergence of generative AI in late 2022 has influenced labour market dynamics. The insights generated will support governments and employers in making informed, data-driven decisions on workforce planning, skills development, and AI adoption strategies.

### **1.1 Business Questions**



#### 1. Temporal Trends

1. How has the AI adoption rate changed quarter-over-quarter since the emergence of generative AI in Q4 2022?
2. Is the rate of job displacement accelerating or stabilizing across 2023 and 2024?

#### 2. Industry and Skill Analysis

3. Which industries exhibit high automation susceptibility but low AI investment, indicating under-preparedness for AI transformation?
4. Which skill categories have the largest gap between AI replaceability and the time required for workforce reskilling?

#### 3. Country-Level Analysis

5. Do countries with more mature AI policies achieve better job creation-to-displacement ratios?
6. Which regions show the greatest disparities in AI adoption between developed and emerging economies?

#### 4. Reskilling and Investment

7. Is investment in workforce reskilling keeping pace with the number of jobs displaced by AI across industries?
8. Which country–industry combinations exhibit the largest gap between displacement risk and reskilling investment?

#### 5. Strategic Insights

9. Which countries, industries, and skill categories are best positioned to benefit from AI adoption?
10. What workforce strategies should governments and employers prioritize to minimize displacement while maximizing the benefits of AI adoption?

### **2. Data Understanding**

#### Dataset Overview

| Table Name | Type | Description | Purpose |
|------------|------|-------------|---------|
| `fact_workforce_ai_index` | Fact Table | Contains the measurable AI workforce metrics and links to all dimension tables through foreign keys. | Used for analysis, KPI calculations, and visualizations. |
| `dim_country` | Dimension Table | Stores country-related information such as country name and geographical classifications. | Enables country and regional analysis. |
| `dim_date` | Dimension Table | Contains date attributes such as year, month, and other time-related fields. | Supports trend and time-series analysis. |
| `dim_industry` | Dimension Table | Contains industry names and classifications. | Enables comparison of AI workforce metrics across industries. |
| `dim_skill_category` | Dimension Table | Stores information about AI skill categories. | Supports analysis of workforce skills and skill demand. |

### **Data Loading for Each Table**

In [1]:
import pandas as pd
import numpy as np

In [5]:
# Load the dataset
country_df = pd.read_csv(r"C:\Users\a-dmin\Documents\Data Science Projects\OnyxDataDNAChallenge\Data\dim_country.csv")
date_df = pd.read_csv(r"C:\Users\a-dmin\Documents\Data Science Projects\OnyxDataDNAChallenge\Data\dim_date.csv")
industry_df = pd.read_csv(r"C:\Users\a-dmin\Documents\Data Science Projects\OnyxDataDNAChallenge\Data\dim_industry.csv")
skill_df = pd.read_csv(r"C:\Users\a-dmin\Documents\Data Science Projects\OnyxDataDNAChallenge\Data\dim_skill_category.csv")
fact_df = pd.read_csv(r"C:\Users\a-dmin\Documents\Data Science Projects\OnyxDataDNAChallenge\Data\fact_workforce_ai_index.csv")

In [8]:
# Create a dictinary for the datasets
datasets = {
    "Country": country_df,
    "Date": date_df,
    "Industry": industry_df,
    "Skill": skill_df,
    "Fact": fact_df
}

In [17]:
# Display the first 3 rows of each dataset
for name, df in datasets.items():
    print(name)
    display(df.head(3))

Country

,country_id,country_code,country_name,region,development_tier,gdp_per_capita_usd,digital_infrastructure_score,ai_policy_maturity,internet_penetration_pct,stem_graduates_per_100k
0,1,US,United States,North America,Developed,33586746.94,65.5,Nascent,95.5,2270.0
1,2,GB,United Kingdom,Europe,Developed,17661249.01,79.5,Developing,84.8,1792.0
2,3,DE,Germany,Europe,Developed,42266884.66,87.3,Developing,88.7,2364.0

Date

,date_id,year,quarter,year_quarter_label,period_start_date,is_pandemic_period,generative_ai_era
0,1,2021,1,2021-Q1,2021-01-01,True,False
1,2,2021,2,2021-Q2,2021-04-01,True,False
2,3,2021,3,2021-Q3,2021-07-01,True,False

Industry

,industry_id,industry_name,industry_sector,automation_susceptibility,avg_ai_investment_pct_revenue,ai_adoption_stage,global_workforce_millions,primary_ai_use_case
0,1,Information Technology,Technology,51.8,1.62,Scaling,12.1,Predictive analytics & code generation
1,2,Financial Services,Finance,53.9,6.58,Exploring,61.4,Fraud detection & algorithmic trading
2,3,Healthcare,Healthcare,45.0,1.50,Piloting,22.9,Diagnostic imaging & drug discovery

Skill

,skill_category_id,skill_category_name,skill_category_code,ai_replaceability_score,ai_augmentation_potential,median_reskilling_duration_months,typical_education_level,global_worker_share_pct
0,1,Cognitive & Analytical,COG-ANL,20.9,93.1,19.6,Bachelor's degree or higher,6.9
1,2,Manual & Physical,MAN-PHY,36.9,66.1,14.9,Vocational / on-the-job training,7.9
2,3,Creative & Design,CRE-DES,39.6,74.0,9.7,Bachelor's degree or portfolio-based,11.0

Fact

,index_id,country_id,industry_id,skill_category_id,date_id,ai_adoption_rate,productivity_impact_score,displacement_risk_index,jobs_displaced_count,jobs_created_count,reskilling_investment_usd,avg_wage_change_pct,ai_tool_usage_hours_per_week,workforce_size,data_confidence_score
0,1,3,21,1,1,24.72,2.01,6.05,3739,2846,139083.86,1.74,1.5,62649,0.798
1,2,26,12,7,7,20.47,6.09,3.46,90,32,13439.86,5.39,1.4,4411,0.855
2,3,21,23,7,8,54.48,6.38,7.69,4080,2337,107635.90,-1.64,10.0,61499,0.772

In [11]:
# Check shaape of each datasets
for name, df in datasets.items():
    print(name)
    print(df.shape)

Country
(30, 10)
Date
(16, 7)
Industry
(25, 8)
Skill
(8, 8)
Fact
(300, 15)

In [12]:
# Check for missing values in each dataset
for name, df in datasets.items():
    print(name)
    print(df.isnull().sum())

Country
country_id                      0
country_code                    0
country_name                    0
region                          0
development_tier                0
gdp_per_capita_usd              0
digital_infrastructure_score    0
ai_policy_maturity              0
internet_penetration_pct        0
stem_graduates_per_100k         0
dtype: int64
Date
date_id               0
year                  0
quarter               0
year_quarter_label    0
period_start_date     0
is_pandemic_period    0
generative_ai_era     0
dtype: int64
Industry
industry_id                      0
industry_name                    0
industry_sector                  0
automation_susceptibility        0
avg_ai_investment_pct_revenue    0
ai_adoption_stage                0
global_workforce_millions        0
primary_ai_use_case              0
dtype: int64
Skill
skill_category_id                    0
skill_category_name                  0
skill_category_code                  0
ai_replaceability_score              0
ai_augmentation_potential            0
median_reskilling_duration_months    0
typical_education_level              0
global_worker_share_pct              0
dtype: int64
Fact
index_id                        0
country_id                      0
industry_id                     0
skill_category_id               0
date_id                         0
ai_adoption_rate                0
productivity_impact_score       0
displacement_risk_index         0
jobs_displaced_count            0
jobs_created_count              0
reskilling_investment_usd       0
avg_wage_change_pct             9
ai_tool_usage_hours_per_week    9
workforce_size                  0
data_confidence_score           0
dtype: int64

In [13]:
# Describe each dataset
for name, df in datasets.items():

    print(name)

    display(df.describe(include="all"))

Country

,country_id,country_code,country_name,region,development_tier,gdp_per_capita_usd,digital_infrastructure_score,ai_policy_maturity,internet_penetration_pct,stem_graduates_per_100k
count,30.000000,30,30,30,30,3.000000e+01,30.000000,30,30.000000,30.000000
unique,NaN,30,30,6,2,NaN,NaN,4,NaN,NaN
top,NaN,US,United States,Europe,Developed,NaN,NaN,Developing,NaN,NaN
freq,NaN,1,1,10,17,NaN,NaN,15,NaN,NaN
mean,15.500000,NaN,NaN,NaN,NaN,2.083839e+07,65.273333,NaN,74.543333,1660.366667
std,8.803408,NaN,NaN,NaN,NaN,1.288010e+07,14.661019,NaN,14.359202,588.712299
min,1.000000,NaN,NaN,NaN,NaN,4.133386e+06,35.500000,NaN,50.100000,377.000000
25%,8.250000,NaN,NaN,NaN,NaN,7.934483e+06,54.350000,NaN,62.550000,1412.000000
50%,15.500000,NaN,NaN,NaN,NaN,1.846721e+07,66.850000,NaN,77.450000,1770.000000
75%,22.750000,NaN,NaN,NaN,NaN,3.353452e+07,75.825000,NaN,86.150000,2046.750000
max,30.000000,NaN,NaN,NaN,NaN,4.226688e+07,88.500000,NaN,99.500000,2798.000000

Date

,date_id,year,quarter,year_quarter_label,period_start_date,is_pandemic_period,generative_ai_era
count,16.000000,16.000000,16.000000,16,16,16,16
unique,NaN,NaN,NaN,16,16,2,2
top,NaN,NaN,NaN,2021-Q1,2021-01-01,False,True
freq,NaN,NaN,NaN,1,1,11,9
mean,8.500000,2022.500000,2.500000,NaN,NaN,NaN,NaN
std,4.760952,1.154701,1.154701,NaN,NaN,NaN,NaN
min,1.000000,2021.000000,1.000000,NaN,NaN,NaN,NaN
25%,4.750000,2021.750000,1.750000,NaN,NaN,NaN,NaN
50%,8.500000,2022.500000,2.500000,NaN,NaN,NaN,NaN
75%,12.250000,2023.250000,3.250000,NaN,NaN,NaN,NaN
max,16.000000,2024.000000,4.000000,NaN,NaN,NaN,NaN

Industry

,industry_id,industry_name,industry_sector,automation_susceptibility,avg_ai_investment_pct_revenue,ai_adoption_stage,global_workforce_millions,primary_ai_use_case
count,25.000000,25,25,25.000000,25.000000,25,25.000000,25
unique,NaN,25,8,NaN,NaN,4,NaN,25
top,NaN,Information Technology,Industrial,NaN,NaN,Piloting,NaN,Predictive analytics & code generation
freq,NaN,1,6,NaN,NaN,8,NaN,1
mean,13.000000,NaN,NaN,54.328000,2.825600,NaN,89.324000,NaN
std,7.359801,NaN,NaN,20.926369,1.371198,NaN,121.797931,NaN
min,1.000000,NaN,NaN,12.100000,1.310000,NaN,8.600000,NaN
25%,7.000000,NaN,NaN,41.900000,1.740000,NaN,24.800000,NaN
50%,13.000000,NaN,NaN,53.900000,2.500000,NaN,47.400000,NaN
75%,19.000000,NaN,NaN,64.800000,3.300000,NaN,80.300000,NaN
max,25.000000,NaN,NaN,95.000000,6.580000,NaN,526.200000,NaN

Skill

,skill_category_id,skill_category_name,skill_category_code,ai_replaceability_score,ai_augmentation_potential,median_reskilling_duration_months,typical_education_level,global_worker_share_pct
count,8.00000,8,8,8.000000,8.000000,8.000000,8,8.000000
unique,NaN,8,8,NaN,NaN,NaN,8,NaN
top,NaN,Cognitive & Analytical,COG-ANL,NaN,NaN,NaN,Bachelor's degree or higher,NaN
freq,NaN,1,1,NaN,NaN,NaN,1,NaN
mean,4.50000,NaN,NaN,43.337500,64.675000,10.225000,NaN,12.500000
std,2.44949,NaN,NaN,17.523122,16.834722,4.779047,NaN,5.971839
min,1.00000,NaN,NaN,20.900000,35.300000,4.900000,NaN,6.900000
25%,2.75000,NaN,NaN,34.950000,61.775000,7.450000,NaN,7.725000
50%,4.50000,NaN,NaN,40.850000,66.200000,8.950000,NaN,11.350000
75%,6.25000,NaN,NaN,48.825000,68.675000,11.150000,NaN,14.325000
max,8.00000,NaN,NaN,79.600000,93.100000,19.600000,NaN,24.000000

Fact

,index_id,country_id,industry_id,skill_category_id,date_id,ai_adoption_rate,productivity_impact_score,displacement_risk_index,jobs_displaced_count,jobs_created_count,reskilling_investment_usd,avg_wage_change_pct,ai_tool_usage_hours_per_week,workforce_size,data_confidence_score
count,300.000000,300.000000,300.000000,300.000000,300.000000,300.000000,300.000000,300.000000,300.000000,300.000000,3.000000e+02,291.000000,291.000000,300.000000,300.000000
mean,150.500000,15.563333,13.580000,4.560000,8.343333,30.646467,5.362067,4.264800,1955.950000,987.850000,2.055050e+05,1.228282,4.842268,77306.313333,0.796093
std,86.746758,8.538678,7.372796,2.251659,4.468259,16.508854,2.005168,2.010153,3172.323594,1468.131359,4.997389e+05,4.349630,3.601537,117405.463453,0.123924
min,1.000000,1.000000,1.000000,1.000000,1.000000,0.500000,0.000000,0.000000,0.000000,0.000000,4.142170e+03,-12.330000,0.000000,2606.000000,0.341000
25%,75.750000,9.000000,7.000000,3.000000,4.000000,18.540000,3.995000,2.890000,325.750000,158.000000,3.346718e+04,-1.450000,2.100000,16836.250000,0.732000
50%,150.500000,15.500000,14.000000,5.000000,8.000000,29.680000,5.500000,4.270000,888.500000,455.000000,8.445774e+04,1.100000,4.700000,36778.500000,0.814000
75%,225.250000,23.000000,20.000000,7.000000,12.000000,41.672500,6.707500,5.422500,2285.750000,1151.750000,2.029119e+05,4.050000,7.050000,88397.250000,0.888250
max,300.000000,30.000000,25.000000,8.000000,16.000000,80.330000,10.000000,10.000000,30973.000000,10585.000000,6.936681e+06,15.270000,16.100000,826001.000000,0.999000

In [14]:
# Check for Duplicates in each dataset
for name, df in datasets.items():
    print(name)
    print(df.duplicated().sum())

Country
0
Date
0
Industry
0
Skill
0
Fact
0

**Insights:**

- The tables are in a star schema format where we have 1 fact table containing measurable values and 4 dimension tables providing descreptive information. 
- Only the fact table has missing values on columns "average-wage-pct" and "ai_tool_usage_hours_per_week" of 9 each.